version: '3.8'

services:
  db:
    image: postgres:18-alpine
    container_name: ptms_db
    restart: always
    environment:
      POSTGRES_DB: ptms_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Wa≈ºne: Kolega ma ten plik w folderze database/ obok tego pliku yaml
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: marekmaro8/ptms-backend:latest # Pobiera gotowy obraz z Hub-a
    container_name: ptms_backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://db:5432/ptms_db
      DB_USERNAME: postgres
      DB_PASSWORD: ${DB_PASSWORD}

  frontend:
    image: marekmaro8/ptms-frontend:latest # Pobiera gotowy obraz z Hub-a
    container_name: ptms_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data: