version: '3.8'

services:
  # 1. BAZA DANYCH (Lokalna w Dockerze)
  db:
    image: postgres:18-alpine
    container_name: ptms_db
    restart: always
    environment:
      POSTGRES_DB: ptms_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. BACKEND
  backend:
    image: marekmaro8/ptms-backend:latest
    container_name: ptms_backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://db:5432/ptms_db
      DB_USERNAME: postgres
      DB_PASSWORD: password
      JWT_SECRET: ZmFzaW9uX3Bhc3N3b3JkXzEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEy

  # 3. FRONTEND
  frontend:
    image: marekmaro8/ptms-frontend:latest
    container_name: ptms_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
